{% set name = "pytest-json-report" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2dde3c647851a19b5f3700729e8310a6e66efb2077d674f27ddea3d34dc615de

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pytest >=3.8.0
    - pytest-metadata
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_jsonreport

about:
  home: https://pypi.org/project/pytest-json-report/
  summary: A pytest plugin to report test results as JSON files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
    - megies
